################################################################################
#
# Vagrantfile
# Adapted from https://buildroot.org/downloads/Vagrantfile
# Author: Jackson Dagger
# Email: JacksonDDagger@gmail.com
# Date: July 26, 2021
#
# This Vagrantfile is for building PIM-swap on a virtualbox VM. The wiki for
# PIM-swap can be found at https://wiki.ubc.ca/PIM-SWAP? and the repo at
# https://github.com/UBC-ECE-Sasha/PIM-swap
################################################################################

# Buildroot version to use
BR_RELEASE='2021.02.2'

### Change here for more memory/cores ###
VM_MEMORY=4096
VM_CORES=2

Vagrant.configure('2') do |config|
	config.vm.box = 'ubuntu/bionic64'

	config.vm.provider :vmware_fusion do |v, override|
		v.vmx['memsize'] = VM_MEMORY
		v.vmx['numvcpus'] = VM_CORES
	end

	config.vm.provider :virtualbox do |v, override|
		v.memory = VM_MEMORY
		v.cpus = VM_CORES

		required_plugins = %w( vagrant-vbguest )
		required_plugins.each do |plugin|
		  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
		end
	end

	config.vm.synced_folder "src/", "/home/vagrant/src"

	config.vm.provision 'shell' do |s|
		s.inline = 'echo Setting up machine name'

		config.vm.provider :vmware_fusion do |v, override|
			v.vmx['displayname'] = "PIM-swap build"
		end

		config.vm.provider :virtualbox do |v, override|
			v.name = "PIM-swap build"
		end
	end

	config.vm.provision 'shell', privileged: true, inline:
		"
		sed -i 's|deb http://us.archive.ubuntu.com/ubuntu/|deb mirror://mirrors.ubuntu.com/mirrors.txt|g' /etc/apt/sources.list
		dpkg --add-architecture i386
		apt-get -q update
		apt-get purge -q -y snapd lxcfs lxd ubuntu-core-launcher snap-confine
		apt-get -q -y install build-essential libncurses5-dev \
			git bzr cvs mercurial subversion libc6:i386 unzip bc \
			libelf-dev libssl-dev make gcc g++ binutils qemu-utils \
			dh-autoconf
		apt-get -q -y autoremove
		apt-get -q -y clean
		update-locale LC_ALL=C
		"

	config.vm.provision 'shell', privileged: false, inline:
		"
		echo 'Downloading and extracting buildroot #{BR_RELEASE}'
		wget -q -c http://buildroot.org/downloads/buildroot-#{BR_RELEASE}.tar.gz
		tar axf buildroot-#{BR_RELEASE}.tar.gz
		mv buildroot-#{BR_RELEASE} src/buildroot
		"
	config.vm.provision 'shell', privileged: false, inline:
		"
		echo 'Downloading and extracting PIM-swap HEAD'
		git clone https://github.com/UBC-ECE-Sasha/PIM-swap src/PIM-swap
		"
	config.vm.provision 'shell', privileged: false, inline:
		"
		echo '#!/bin/sh' >> src/PIM-swap/.env
		echo 'export PIMSWAP_SITE=/home/vagrant/PIM-swap' >> src/PIM-swap/.env
		echo 'export PIMSWAP_OVERRIDE_SRCDIR=/home/vagrant/PIM-swap/module' >> src/PIM-swap/.env
		"
end
